version: "3"

networks:
  jnu_hlfn:
    external:
      name: artifacts_jnu_hlfn

services:
  client-app:
    image: woojae9488/fabric-survey-client:1.1
    container_name: client-app
    environment:
      - VUE_APP_API_ADDR=http://${PUBLIC_IP}:8090
      - CC_PATH=/usr/src/app/src/chaincode
    volumes:
      - ../chaincode/:/usr/src/app/src/chaincode/
    ports:
      - 8080:8080
    networks:
      - jnu_hlfn
    depends_on:
      - server-app

  server-app:
    image: woojae9488/fabric-survey-server:1.1
    container_name: server-app
    volumes:
      - ./docker-config/.env.server:/usr/src/app/.env
      - ./docker-config/manager-connection.json:/usr/src/app/fabric/manager-connection.json
      - ./docker-config/student-connection.json:/usr/src/app/fabric/student-connection.json
      - ../artifacts/network/crypto-config/:/tmp/crypto/
    ports:
      - 8090:8090
    networks:
      - jnu_hlfn
